# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7k325tfbg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Xilinx_my_IP [current_project]
set_property ip_output_repo c:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cpu/rtl/cpu_cfig.h
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_dmi_define.h
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_define.h
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/sysmap.h
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_cfig.h
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/idu/rtl/aq_idu_cfig.h
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/dtu/rtl/aq_dtu_cfig.h
}
set_property file_type "Verilog Header" [get_files C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cpu/rtl/cpu_cfig.h]
set_property is_global_include true [get_files C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cpu/rtl/cpu_cfig.h]
set_property file_type "Verilog Header" [get_files C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_dmi_define.h]
set_property is_global_include true [get_files C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_dmi_define.h]
set_property file_type "Verilog Header" [get_files C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_define.h]
set_property is_global_include true [get_files C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_define.h]
set_property file_type "Verilog Header" [get_files C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/sysmap.h]
set_property is_global_include true [get_files C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/sysmap.h]
set_property file_type "Verilog Header" [get_files C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_cfig.h]
set_property is_global_include true [get_files C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_cfig.h]
set_property file_type "Verilog Header" [get_files C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/idu/rtl/aq_idu_cfig.h]
set_property is_global_include true [get_files C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/idu/rtl/aq_idu_cfig.h]
set_property file_type "Verilog Header" [get_files C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/dtu/rtl/aq_dtu_cfig.h]
set_property is_global_include true [get_files C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/dtu/rtl/aq_dtu_cfig.h]
read_verilog -library xil_defaultlib {
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/common/rtl/BUFGCE.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/ahb/ahb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/ahb/ahb2apb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/apb/apb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/apb/apb_bridge.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/biu/rtl/aq_biu_apbif.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/biu/rtl/aq_biu_read_channel.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/biu/rtl/aq_biu_req_arbiter.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/biu/rtl/aq_biu_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/biu/rtl/aq_biu_write_channel.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/biu/rtl/aq_biu_wt_entry.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cpu/rtl/aq_core.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cp0/rtl/aq_cp0_cache_inst.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cp0/rtl/aq_cp0_ext_csr.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cp0/rtl/aq_cp0_fence_inst.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cp0/rtl/aq_cp0_float_csr.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cp0/rtl/aq_cp0_hpcp_csr.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cp0/rtl/aq_cp0_info_csr.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cp0/rtl/aq_cp0_iui.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cp0/rtl/aq_cp0_lpmd.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cp0/rtl/aq_cp0_prtc_csr.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cp0/rtl/aq_cp0_regs.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cp0/rtl/aq_cp0_rst_ctrl.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cp0/rtl/aq_cp0_special.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cp0/rtl/aq_cp0_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cp0/rtl/aq_cp0_trap_csr.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cp0/rtl/aq_cp0_vector_inst.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cpu/rtl/aq_cpuio_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_dcache_data_array.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_dcache_dirty_array.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_dcache_tag_array.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_dcache_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/dtu/rtl/aq_dtu_cdc.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/dtu/rtl/aq_dtu_cdc_lvl.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/dtu/rtl/aq_dtu_cdc_pulse.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/dtu/rtl/aq_dtu_ctrl.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/dtu/rtl/aq_dtu_dbginfo.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/dtu/rtl/aq_dtu_iie_trigger.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/dtu/rtl/aq_dtu_m_iie_all.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/dtu/rtl/aq_dtu_mcontrol.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/dtu/rtl/aq_dtu_mcontrol_output_select.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/dtu/rtl/aq_dtu_pcfifo.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/dtu/rtl/aq_dtu_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/dtu/rtl/aq_dtu_trigger_module.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/fpga/rtl/aq_f_spsram_1024x16.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/fpga/rtl/aq_f_spsram_1024x64.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/fpga/rtl/aq_f_spsram_128x8.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/fpga/rtl/aq_f_spsram_2048x32.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/fpga/rtl/aq_f_spsram_256x59.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/fpga/rtl/aq_f_spsram_64x58.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/fpga/rtl/aq_f_spsram_64x88.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/fpga/rtl/aq_f_spsram_64x98.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_fadd_double_add.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_fadd_double_cmp_max.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_fadd_double_dp.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_fadd_double_round.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_fadd_double_special.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_fadd_double_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_fadd_lop_s1_sb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_fadd_scalar_dp.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_fadd_shift_sub_h_double.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_fadd_shift_sub_single.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_falu_ctrl.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_falu_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_fcnvt_ctrl.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_fcnvt_double.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_fcnvt_dtos_d.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_fcnvt_ftoi_d.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_fcnvt_scalar_dp.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_fcnvt_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_fcnvt_xtoh_sh.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfdsu/rtl/aq_fdsu_denorm_shift.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfdsu/rtl/aq_fdsu_double.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfdsu/rtl/aq_fdsu_double_dp.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfdsu/rtl/aq_fdsu_pack.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfdsu/rtl/aq_fdsu_prepare.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfdsu/rtl/aq_fdsu_right_shift.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfdsu/rtl/aq_fdsu_round.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfdsu/rtl/aq_fdsu_scalar_ctrl.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfdsu/rtl/aq_fdsu_scalar_dp.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfdsu/rtl/aq_fdsu_special.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfdsu/rtl/aq_fdsu_srt.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfdsu/rtl/aq_fdsu_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_fspu_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/pmu/rtl/aq_hpcp_adder_sel.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/pmu/rtl/aq_hpcp_cnt.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/pmu/rtl/aq_hpcp_cntinten_reg.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/pmu/rtl/aq_hpcp_cntof_reg.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/pmu/rtl/aq_hpcp_event.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/pmu/rtl/aq_hpcp_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/idu/rtl/aq_idu_expand_32.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/idu/rtl/aq_idu_id_ctrl.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/idu/rtl/aq_idu_id_decd.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/idu/rtl/aq_idu_id_dp.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/idu/rtl/aq_idu_id_gpr.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/idu/rtl/aq_idu_id_gpr_gated_reg.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/idu/rtl/aq_idu_id_split.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/idu/rtl/aq_idu_id_wbt.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/idu/rtl/aq_idu_id_wbt_entry.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/idu/rtl/aq_idu_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_bht.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_bht_array.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_btb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_btb_entry.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_ctrl.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_ibuf.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_ibuf_entry.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_ibuf_pop_entry.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_icache.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_icache_data_array.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_icache_tag_array.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_ipack.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_ipack_entry.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_pcgen.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_pre_decd.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_pred.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_ras.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_ras_entry.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_ifu_vec.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/iu/rtl/aq_iu_addr_gen.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/iu/rtl/aq_iu_alu.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/iu/rtl/aq_iu_bju.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/iu/rtl/aq_iu_div.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/iu/rtl/aq_iu_div_shift2_kernel.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/iu/rtl/aq_iu_mul.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/iu/rtl/aq_iu_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_left_shift_64.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_ag.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_amo_alu.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_amr.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_arb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_dc.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_dtif.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_icc.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_lfb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_lfb_entry.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_lm.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_mcic.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_pfb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_pfb_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_rdl.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_stb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_stb_entry.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_lsu_vb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/aq_mmu_arb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/aq_mmu_jtlb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/aq_mmu_jtlb_data_array.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/aq_mmu_jtlb_tag_array.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/aq_mmu_plru.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/aq_mmu_ptw.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/aq_mmu_regs.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/aq_mmu_sysmap.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/aq_mmu_sysmap_hit.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/aq_mmu_tlboper.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/aq_mmu_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/aq_mmu_utlb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/aq_mmu_utlb_entry.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/aq_mmu_utlb_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/clk/rtl/aq_mp_clk_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/rst/rtl/aq_mp_rst_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/pmp/rtl/aq_pmp_acc.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/pmp/rtl/aq_pmp_comp_hit.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/pmp/rtl/aq_pmp_regs.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/pmp/rtl/aq_pmp_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_prio.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/rtu/rtl/aq_rtu_ctrl.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/rtu/rtl/aq_rtu_dp.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/rtu/rtl/aq_rtu_int.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/rtu/rtl/aq_rtu_rbus.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/rtu/rtl/aq_rtu_retire.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/rtu/rtl/aq_rtu_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/rtu/rtl/aq_rtu_wb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_spsram_1024x16.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_spsram_1024x64.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_spsram_128x8.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_spsram_2048x32.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/ifu/rtl/aq_spsram_256x59.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_spsram_64x58.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/aq_spsram_64x88.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/mmu/rtl/aq_spsram_64x98.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cpu/rtl/aq_sysio_kid.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cpu/rtl/aq_sysio_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cpu/rtl/aq_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfalu/rtl/aq_vdsp_64_bit_ff1.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vdiv/rtl/aq_vdsp_8_bit_ff1.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfmau/rtl/aq_vfmau_ctrl.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfmau/rtl/aq_vfmau_dp.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfmau/rtl/aq_vfmau_frac_mult.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfmau/rtl/aq_vfmau_frac_shift_double.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfmau/rtl/aq_vfmau_lza_double.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfmau/rtl/aq_vfmau_mult.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfmau/rtl/aq_vfmau_mult_double.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfmau/rtl/aq_vfmau_multiplier_53x27_partial.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfmau/rtl/aq_vfmau_special_judge_double.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfmau/rtl/aq_vfmau_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vidu/rtl/aq_vidu_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vidu/rtl/aq_vidu_vid_ctrl_fp.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vidu/rtl/aq_vidu_vid_dp_fp.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vidu/rtl/aq_vidu_vid_gpr_fp.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vidu/rtl/aq_vidu_vid_gpr_reg_fp.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vidu/rtl/aq_vidu_vid_split_fp.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vidu/rtl/aq_vidu_vid_wbt.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vidu/rtl/aq_vidu_vid_wbt_entry.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_vlsu_data_trans.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_vlsu_ld_align_buffer.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_vlsu_lsu_if.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_vlsu_rot_data.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_vlsu_st_align_buffer.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_vlsu_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_vlsu_vtb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/lsu/rtl/aq_vlsu_vtb_entry.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vdsp/rtl/aq_vpu_fwd_wb_rbus.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vdsp/rtl/aq_vpu_group_unit.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vdsp/rtl/aq_vpu_srcv_type.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vdsp/rtl/aq_vpu_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vdsp/rtl/aq_vpu_viq_dp.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/axi/axi2ahb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/axi/axi_err128.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/axi/axi_fifo.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/axi/axi_fifo_entry.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/axi/axi_interconnect128.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/axi/axi_slave128.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/iu/rtl/booth_code_33_bit.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/vfmau/rtl/booth_code_54_bit.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/bus/bus_delay.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/clint/rtl/clint_func.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/clint/rtl/clint_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/common/cpu_sub_system_axi.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/plic/rtl/csky_apb_1tox_matrix.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/common/err_gen.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/mem/f_spsram_32768x128.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/common/fifo_counter.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/clk/fpga_clk_gen.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/fpga/rtl/fpga_ram.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/gpio/gpio.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/gpio/gpio_apbif.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/gpio/gpio_ctrl.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/mem/mem_ctrl.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/iu/rtl/multiplier_33x33_partial.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cpu/rtl/openC906.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/plic/rtl/plic_32to1_arb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/plic/rtl/plic_arb_ctrl.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/plic/rtl/plic_ctrl.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/plic/rtl/plic_granu2_arb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/plic/rtl/plic_granu_arb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/plic/rtl/plic_hart_arb.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/plic/rtl/plic_hreg_busif.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/plic/rtl/plic_int_kid.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/plic/rtl/plic_kid_busif.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/plic/rtl/plic_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/mem/ram.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/common/soc.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/common/rtl/sync_level2level.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_apb_master.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dm.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dm_pulse_sync.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dm_sync_dff.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_dm_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_dmi.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dmi_pulse_sync.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_dmi_rst_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dmi_sync_dff.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_dmi_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dtm_chain.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dtm_ctrl.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dtm_idr.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dtm_io.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dtm_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/common/tdt_gated_clk_cell.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_sba_axi.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/common/timer.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/common/tr_axi_interconnect.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/uart/uart.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/uart/uart_apb_reg.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/uart/uart_baud_gen.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/uart/uart_ctrl.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/uart/uart_receive.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/uart/uart_trans.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/common/wid_entry.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/new/openc906_top.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/smart_run/logical/mem/f_spsram_524288x128.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/imports/openc906/C906_RTL_FACTORY/gen_rtl/cpu/rtl/mp_top_golden_port.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/new/init_ram.v
  C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/new/init_f_spsram_32768x128.v
}
read_ip -quiet C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/constrs_1/new/c906.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/RISCV_FPGA/openc906_FPGA/openc906_FPGA.srcs/constrs_1/new/c906.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top openc906_top -part xc7k325tfbg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef openc906_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file openc906_top_utilization_synth.rpt -pb openc906_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
