create_clock -period 40.000 -name clk_in -waveform {0.000 20.000} [get_ports clk_in]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[12]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[12]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[13]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[13]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[14]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[14]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[15]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[15]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[16]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[16]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[17]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[17]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[18]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[18]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[19]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[19]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[20]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[20]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[21]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[21]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[22]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[22]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[23]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[23]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[24]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[24]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[25]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[25]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[26]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[26]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[27]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[27]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[28]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[28]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[29]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[29]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[30]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[30]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[31]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[31]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[32]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[32]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[33]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[33]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[34]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[34]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[35]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[35]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[36]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[36]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[37]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[37]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[38]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[38]/Q}]
create_generated_clock -name {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg_n_0_[39]} -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins {x_soc/x_apb/x_apb_bridge/apb_xx_paddr_reg[39]/Q}]
create_generated_clock -name x_soc/x_apb/x_apb_bridge/apb_xx_psel -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins x_soc/x_apb/x_apb_bridge/apb_xx_psel_reg/Q]
create_generated_clock -name x_soc/x_apb/x_apb_bridge/apb_xx_pwrite -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins x_soc/x_apb/x_apb_bridge/apb_xx_pwrite_reg/Q]
create_generated_clock -name x_soc/x_cpu_sub_system_axi/x_c906_wrapper/sys_apb_clk -source [get_pins sysclk/inst/plle2_adv_inst/CLKOUT0] -divide_by 1 [get_pins x_soc/x_cpu_sub_system_axi/x_c906_wrapper/sys_apb_clk_reg/Q]
set_property PACKAGE_PIN L21 [get_ports uart0_sout_tx]
set_property PACKAGE_PIN K21 [get_ports uart0_sin_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uart0_sin_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uart0_sout_tx]
set_property IOSTANDARD LVCMOS18 [get_ports clk_in]
set_property PACKAGE_PIN D12 [get_ports clk_in]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]


set_property MARK_DEBUG false [get_nets uart0_sin_rx_IBUF]
set_property MARK_DEBUG false [get_nets uart0_sout_tx_OBUF]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list sysclk/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 40 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[0]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[1]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[2]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[3]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[4]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[5]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[6]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[7]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[8]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[9]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[10]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[11]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[12]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[13]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[14]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[15]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[16]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[17]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[18]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[19]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[20]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[21]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[22]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[23]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[24]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[25]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[26]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[27]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[28]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[29]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[30]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[31]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[32]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[33]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[34]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[35]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[36]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[37]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[38]} {x_soc/x_cpu_sub_system_axi/biu_pad_awaddr[39]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list x_soc/x_cpu_sub_system_axi/biu_pad_awvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list x_soc/i_pad_uart0_sin]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list x_soc/o_pad_uart0_sout]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_100m]
